export const homeObjTwo = {
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "FrontEnd",
  description: "Engage with users through well designed frontend.",
  buttonLabel: "Contact",
  img: require("../../images/undraw_social_thinking_re_y8cc.svg").default,
  start: "",
  alt: "Image",
  id: "frontend",
  viewButton: false,
  circle: true,
  img0: require("../../images/techLogos/frontend/React.png"),
  img60: require("../../images/techLogos/frontend/NewHTML5.png"),
  img120: require("../../images/techLogos/frontend/Sass.png"),
  img180: require("../../images/techLogos/frontend/Gatsby_Monogram.png"),
  img240: require("../../images/techLogos/frontend/bootstrap-logo.png"),
  img300: require("../../images/techLogos/frontend/jquery.png")
};