export const homeObjOne = {
  id: "home",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "Developer",
  lightText: false,
  lightTextDesc: false,
  headline: "Liam Smith",
  description: "Using design and data to help people connect.",
  resumeLabel: "Check out my resume",
  img: require("../../images/Headshot-Transparent-BG.png"),
  start: "false",
  alt: "Image",
  viewButton: true,
  socialIconLI: require("../../images/socialLogos/LI-In-Bug.png"),
  socialIconGit: require("../../images/socialLogos/github-mark.png"),
  stationary: true
};

export const homeObjTwo = {
  id: "frontend",
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "FrontEnd",
  description: "Some of the front end tech I've worked with over the last 18 months to create appealing UI.",
  buttonLabel: "Contact",
  img: require("../../images/undraw_social_thinking_re_y8cc.svg").default,
  start: "",
  alt: "Image",
  viewButton: false,
  circle: true,
  startCircle: true,
  img0: require("../../images/techLogos/frontend/React.png"),
  img60: require("../../images/techLogos/frontend/NewHTML5.png"),
  img120: require("../../images/techLogos/frontend/Sass.png"),
  img180: require("../../images/techLogos/frontend/Gatsby_Monogram.png"),
  img240: require("../../images/techLogos/frontend/bootstrap-logo.png"),
  img300: require("../../images/techLogos/frontend/jquery.png")
};

export const homeObjThree = {
  id: "backend",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "BackEnd",
  description: "Tech skills I have been developing to manage requests, responses and data on the backend.",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
  circle: true,
  startCircle: false,
  img0: require("../../images/techLogos/backend/JavaScript.png"),
  img60: require("../../images/techLogos/backend/NodeJS.png"),
  img120: require("../../images/techLogos/frontend/Sass.png"),
  img180: require("../../images/techLogos/frontend/Gatsby_Monogram.png"),
  img240: require("../../images/techLogos/frontend/bootstrap-logo.png"),
  img300: require("../../images/techLogos/frontend/jquery.png")
};
export const homeObjFour = {
  id: "about",
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "About Liam",
  description: "I am a developer, musician and humanist with a broad range of interests. I aim to merge arts, development and community, strengthening real world networks and contributing to positive social change. I believe that technology must improve the lives of average people and be used to flatten society.",
  buttonLabel: "",
  img: require("../../images/Headshot-Transparent-BG.png"),
  start: "",
  alt: "Image",
  viewButton: false,
};

export const homeObjFive = {
  id: "projects",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "Projects",
  // description: "Reactjs, HTML, CSS, EJS, SASS",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};


export const footerObj = {
  bgColor: true,
  textColor: true
}