export const homeObjOne = {
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "Web Developer",
  lightText: false,
  lightTextDesc: false,
  headline: "Liam Smith",
  description: "Using design and data to help people connect",
  buttonLabel: "Resume",
  img: require("../../images/Headshot-Transparent-BG.png"),
  start: "",
  alt: "Image",
  viewButton: true,
};

export const homeObjTwo = {
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "Front End",
  description: "Reactjs, HTML, CSS3, EJS, SASS, Bootstrap, Gatsby",
  buttonLabel: "Contact",
  img: require("../../images/undraw_social_thinking_re_y8cc.svg").default,
  start: "",
  alt: "Image",
  viewButton: false,
};

export const homeObjThree = {
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "BackEnd",
  description: "NodeJS, Axiox, Ajax, Express, Rails",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};
export const homeObjFour = {
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "About Liam",
  // description: "Reactjs, HTML, CSS, EJS, SASS",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};

export const homeObjFive = {
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "Projects",
  // description: "Reactjs, HTML, CSS, EJS, SASS",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};
