export const homeObjOne = {
  id: "home",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "Web Developer",
  lightText: false,
  lightTextDesc: false,
  headline: "Liam Smith",
  description: "Using design and data to help people connect",
  buttonLabel: "Resume",
  img: require("../../images/Headshot-Transparent-BG.png"),
  start: "",
  alt: "Image",
  viewButton: true,
};

export const homeObjTwo = {
  id: "frontend",
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "FrontEnd",
  description: "Engage with users through well designed frontend.",
  buttonLabel: "Contact",
  img: require("../../images/undraw_social_thinking_re_y8cc.svg").default,
  start: "",
  alt: "Image",
  viewButton: false,
  circle: true,
  img0: require("../../images/techLogos/frontend/React.png"),
  img60: require("../../images/techLogos/frontend/NewHTML5.png"),
  img120: require("../../images/techLogos/frontend/Sass.png"),
  img180: require("../../images/techLogos/frontend/Gatsby_Monogram.png"),
  img240: require("../../images/techLogos/frontend/bootstrap-logo.png"),
  img300: require("../../images/techLogos/frontend/jquery.png")
};

export const homeObjThree = {
  id: "backend",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "BackEnd",
  description: "Manage requests, responses and data with the right backend for your project.",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
  circle: true,
  img0: require("../../images/techLogos/backend/JavaScript.png"),
  img60: require("../../images/techLogos/backend/NodeJS.png"),
  img120: require("../../images/techLogos/frontend/Sass.png"),
  img180: require("../../images/techLogos/frontend/Gatsby_Monogram.png"),
  img240: require("../../images/techLogos/frontend/bootstrap-logo.png"),
  img300: require("../../images/techLogos/frontend/jquery.png")
};
export const homeObjFour = {
  id: "about",
  lightBg: false,
  primary: true,
  imgStart: "start",
  lightTopLine: true,
  topLine: "",
  lightText: true,
  lightTextDesc: true,
  headline: "About Liam",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};

export const homeObjFive = {
  id: "projects",
  lightBg: true,
  primary: false,
  imgStart: "",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "Projects",
  // description: "Reactjs, HTML, CSS, EJS, SASS",
  buttonLabel: "",
  img: "",
  start: "",
  alt: "Image",
  viewButton: false,
};
