export const homeObjFive = {
  id: "projects",
  lightBg: true,
  primary: false,
  imgStart: "start",
  lightTopLine: false,
  topLine: "",
  lightText: false,
  lightTextDesc: false,
  headline: "Projects",
  description: "Web CRUD app for scheduling a neighbourhood tool rental built with Postgres, Express, React, Node.",
  description2: "An interview scheduling app built with Front-end: Postgres, Express, React, Node and tested with Cypress, Jest, StoryBook",
  description3: "A Twitter clone built with jQuery, HTML5, and CSS.",
  description4: "An app allowing users shorten long URLs (similar to bit.ly). TinyApp is built with Node and Express. NodeJS, Express, EJS",
  buttonLabel: "",
  img: require("../../images/ToolSwap.png"),
  img2: require("../../images/Scheduler.png"),
  img3: require("../../images/Tweeter.png"),
  img4: require("../../images/TinyApp.png"),
  start: "",
  alt: "Image",
  viewButton: false,
};